### ISSUE TITLE
Basic instruction

### ISSUE THREAD

**Issue by gbraad** [trishnaguha/build-atomic-host#1]
`Dockerfile`
```
FROM fedora:25
MAINTAINER Gerard Braad <me@gbraad.nl>

# Run update and install packages
RUN dnf update -y && \
    dnf install -y ansible && \
    dnf clean all

# Create working dir
RUN mkdir -p /workspace
ADD ./compose.yml /workspace

# Compose (result will be in /srv/repo)
RUN cd /workspace && ansible-playbook compose.yml

# Expose web server port, set working dir
EXPOSE 8000
WORKDIR /workspace
VOLUME /workspace

# Start web server
CMD ostree trivial-httpd -p 8000 /srv/repo
```

`compose.yml`
```
#!/usr/bin/env ansible-playbook
---
- hosts: localhost

  tasks:
  - name: Install list of required packages
    package: name={{ item }} state=installed
    become: yes
    become_method: sudo
    with_items:
    - git
    - rpm-ostree

  - name: Clean package cache
    command: >-
      dnf clean all
      
  - name: Create directory structure
    file: path="{{ item }}" state=directory mode=750
    with_items:
    - "/srv/repo"
    - "/workspace"

  - name: Initialize repository
    command: >-
      ostree --repo=/srv/repo init --mode=archive-z2

  - name: Clone Fedora-Atomic buildscripts
    git: >-
      repo=https://pagure.io/fedora-atomic.git
      version=f25
      depth=1
      dest=/workspace/fedora-atomic

  - name: Compose Fedora-Atomic tree
    command: >-
      chdir=/workspace/fedora-atomic/
      rpm-ostree compose tree --repo=/srv/repo ./fedora-atomic-docker-host.json

#  - name: Start webserver
#    command: >-
#      ostree trivial-httpd -p 8000 /srv/repo
```

The Dockerfile might not run as it creates new namespaces during the compose step, however it describes what is needed. Maybe a `Vagrantfile` would have been better. Anyways, this will result in a Atomic host tree that can be served over http as static assets by `nginx` or by `ostree trivial-httpd`. Retested this process at: https://gitlab.com/gbraad/byo-atomic-fedora, Source: https://github.com/gbraad/byo-atomic-fedora

The tree can be used on the Atomic host as:
```
sudo ostree remote add byo-atomic-fedora http://[hostname]:8000 --no-gpg-verify
sudo rpm-ostree rebase byo-atomic-fedora:fedora-atomic/f25/x86_64/docker-host
systemctl reboot
```
